#pragma once
#include <Arduino.h>
namespace bridge {
const char DashboardPage[] PROGMEM = R"BRIDGE(<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Universal LoRa Bridge</title><style>
:root{color-scheme:dark;font:15px system-ui;background:#0b1220;color:#dce6f5}body{max-width:1120px;margin:32px auto;padding:0 18px}h1{margin-bottom:6px}h2{font-size:19px}p{color:#a9bdd8}section{background:#131e30;border:1px solid #2b3b53;border-radius:12px;padding:18px;margin:18px 0}.row{display:flex;gap:12px;flex-wrap:wrap;align-items:center}button,select,input{font:inherit;color:inherit;background:#22324b;border:1px solid #526882;border-radius:6px;padding:8px}button{cursor:pointer}button:hover{background:#314969}input[type=text]{flex:1;min-width:160px}#connection{color:#ffd580}#stats{display:grid;grid-template-columns:repeat(auto-fit,minmax(150px,1fr));gap:12px}.metric{padding:12px;background:#0b1525;border-radius:6px}.metric small{display:block;color:#9fb4ce}.metric strong{font-size:20px}#console{height:350px;overflow:auto;background:#070e18;padding:12px;font:13px ui-monospace,monospace;white-space:pre-wrap;overflow-wrap:anywhere}.entry{padding:3px 0}.tx{color:#83d6ff}.rx{color:#a0e6a4}table{width:100%;text-align:left;border-collapse:collapse}td,th{padding:9px;border-bottom:1px solid #2b3b53}.muted{font-size:13px;color:#a9bdd8}label{display:inline-flex;gap:7px;align-items:center}#status{min-height:22px}a{color:#83d6ff}</style></head>
<body><h1>Universal LoRa Bridge</h1><div id="connection">Connecting to live WebSocket…</div><p id="status">Waiting for Master</p>
<section><h2>Local Master</h2><div id="local">Waiting for status…</div></section>
<section><h2>Link statistics</h2><div id="stats"></div><p class="muted">TX/RX count unique payload chunks, not serial messages. Unconfirmed delivery is retry exhaustion, not a measured RF loss rate. Console drops affect only the displayed copy.</p></section>
<section><h2>Live payload console</h2><div class="row"><label>Display <select id="mode"><option>TEXT</option><option>HEX</option><option>AUTO</option></select></label><label><input id="autoscroll" type="checkbox" checked>Autoscroll</label><button id="clear">Clear</button><span class="muted">Master uptime timestamps · last 500 events</span></div><p class="muted">TX: local serial → LoRa. RX: Remote → LoRa → local serial output queue. Retransmissions are not repeated here.</p><div id="console" role="log" aria-label="Live payload console"></div>
<p class="muted">PRG button test messages also appear here, but go to the receiving OLED only. Hold PRG for 2 seconds and release to open Back / Send message; click to move and double-click to select.</p>
<div class="row" style="margin-top:12px"><select id="sendmode" aria-label="Send format"><option>TEXT</option><option>HEX</option></select><input id="sendtext" type="text" placeholder="Test payload (no newline appended)" aria-label="Test payload"><button id="send">Send over LoRa</button></div><p id="feedback" class="muted" aria-live="polite"></p></section>
<section><h2>Discovered remote nodes</h2><table><thead><tr><th>Node</th><th>Role / peer</th><th>Last heard</th><th>RSSI / SNR</th><th>Pair</th></tr></thead><tbody id="nodes"></tbody></table><p class="muted">Remote pairing opens for 60 seconds after boot or a button double-click. Hold either board’s button for 8 seconds to clear its pairing, or use Unpair locally.</p><button id="unpair">Unpair local Master</button></section>
<section><h2>Settings</h2><div class="row"><label>RF preset <select id="preset"><option value="0">Long Range</option><option value="1">Balanced</option><option value="2">High Speed</option></select></label><label>Hardware UART baud <select id="baud"><option>9600</option><option>19200</option><option>38400</option><option>57600</option><option selected>115200</option><option>230400</option></select></label><button id="apply">Apply to both boards</button></div><p class="muted">Stop serial senders before changing settings. Both boards negotiate a delayed RF/UART change and recover on Balanced if contact is lost. USB serial stays at 115200 baud.</p><div class="row"><label>Local interface <select id="interface"><option value="0">Auto: first incoming activity</option><option value="1">USB serial</option><option value="2">Hardware UART</option></select></label><button id="setinterface">Apply local interface</button></div><p class="muted">Auto locks to the first active input until reset. Before activity, received data goes to USB. UART-only receive devices can select UART with a button single-click when queues are idle.</p></section>
<script>
'use strict';
const $=id=>document.getElementById(id);let ws,events=[],settingsInitialized=false;
const idhex=n=>Number(n).toString(16).toUpperCase().padStart(8,'0');
function clock(ms){const s=Math.floor(ms/1000);return `${Math.floor(s/3600).toString().padStart(2,'0')}:${Math.floor(s/60)%60<10?'0':''}${Math.floor(s/60)%60}:${(s%60).toString().padStart(2,'0')}.${(ms%1000).toString().padStart(3,'0')}`;}
function readable(hex){return hex.match(/../g).map(x=>{const n=parseInt(x,16);return n>=32&&n<=126?String.fromCharCode(n):'\\x'+x;}).join('');}
function line(e){const mode=$('mode').value;const binary=!/^(?:[2-6][0-9A-F]|7[0-E])*$/.test(e.hex);return `${clock(e.timestamp)} ${e.direction} [${e.length}]  `+((mode==='HEX'||(mode==='AUTO'&&binary))?e.hex.match(/../g).join(' '):readable(e.hex));}
function addLine(e){const div=document.createElement('div');div.className='entry '+e.direction.toLowerCase();div.textContent=line(e);$('console').appendChild(div);}
function scroll(){if($('autoscroll').checked)$('console').scrollTop=$('console').scrollHeight;}
function render(){ $('console').replaceChildren();events.forEach(addLine);scroll(); }
function command(value){if(!ws||ws.readyState!==WebSocket.OPEN){$('feedback').textContent='Disconnected; command not sent.';return;}ws.send(value);$('feedback').textContent='Command submitted; watch status for acceptance.';}
function status(s){
 $('status').textContent=s.status;
 $('local').textContent=`${idhex(s.local)} · Master · ${s.linked?'Connected to '+idhex(s.peer):'Waiting for peer'} · active ${s.activeInterface===2?'UART':'USB'} · ${['Long Range','Balanced','High Speed'][s.preset]} · UART ${s.baud}`;
 const completed=s.acknowledged+s.failed;
 const metrics=[['TX packets',s.txPackets],['RX packets',s.rxPackets],['TX bytes',s.txBytes],['RX bytes',s.rxBytes],['ACKed TX',s.acknowledged],['Unconfirmed TX',s.failed],['Unconfirmed rate',completed?(100*s.failed/completed).toFixed(1)+'%':'—'],['Unconfirmed bytes',s.failedBytes],['Retransmissions',s.retries],['Duplicates',s.duplicates],['RSSI',s.seenPacket?s.rssi+' dBm':'—'],['SNR',s.seenPacket?s.snr+' dB':'—'],['TX throughput',s.txRate+' B/s'],['RX throughput',s.rxRate+' B/s'],['TX queue',s.txQueued+'/4288 B'],['RX queue',s.rxQueued+'/4096 B'],['Log queue',s.logQueued+'/24'],['Console drops',s.logDrops],['Backpressure',s.backpressure],['Serial overflows',s.serialOverflows],['Invalid / CRC',s.malformed],['Radio errors',s.radioErrors],['Rejected commands',s.commandRejects],['Device uptime',clock(s.now)],['Link uptime',s.linked?clock((s.now-s.linkSince)>>>0):'—'],['Last peer packet',s.seenPacket?((s.now-s.lastPacket)>>>0)+' ms ago':'—'],['Settings',s.settingsPending?'Transition pending':'Stable']];
 $('stats').replaceChildren(...metrics.map(([name,value])=>{const d=document.createElement('div');d.className='metric';const a=document.createElement('small'),b=document.createElement('strong');a.textContent=name;b.textContent=value;d.append(a,b);return d;}));
 $('nodes').replaceChildren(...s.nodes.map(n=>{const tr=document.createElement('tr');[idhex(n.id),(n.master?'Master':'Remote')+' / '+(n.peer?idhex(n.peer):'unpaired'),((s.now-n.lastHeard)>>>0)+' ms ago',`${n.rssi} / ${n.snr}`].forEach(t=>{const td=document.createElement('td');td.textContent=t;tr.append(td);});const td=document.createElement('td'),b=document.createElement('button');b.textContent=n.id===s.peer?'Paired':'Pair';b.disabled=!!s.peer||n.master||!!n.peer||((s.now-n.lastHeard)>>>0)>30000;b.onclick=()=>command('pair:'+n.id);td.append(b);tr.append(td);return tr;}));
 if(!settingsInitialized){$('preset').value=s.preset;$('baud').value=s.baud;$('interface').value=s.interfaceMode;settingsInitialized=true;}
}
function connect(){ws=new WebSocket(`ws://${location.hostname}:81/ws`);ws.onopen=()=>{$('connection').textContent='Live · WebSocket connected';settingsInitialized=false;};ws.onclose=()=>{$('connection').textContent='Disconnected · reconnecting…';setTimeout(connect,1500);};ws.onerror=()=>ws.close();ws.onmessage=({data})=>{try{const e=JSON.parse(data);if(e.type==='payload'){events.push(e);addLine(e);if(events.length>500){events.shift();$('console').firstChild.remove();}scroll();}else if(e.type==='stats')status(e);else if(e.type==='result')$('feedback').textContent=e.message;}catch(_){$('feedback').textContent='Invalid dashboard event ignored';}};}
$('mode').onchange=render;$('autoscroll').onchange=scroll;$('clear').onclick=()=>{events=[];$('console').replaceChildren();};
$('send').onclick=()=>{let bytes;if($('sendmode').value==='HEX'){const value=$('sendtext').value.replace(/\s/g,'');if(!/^(?:[0-9a-fA-F]{2})+$/.test(value)){$('feedback').textContent='Enter complete HEX bytes, e.g. FD 09 00';return;}bytes=Uint8Array.from(value.match(/../g),x=>parseInt(x,16));}else bytes=new TextEncoder().encode($('sendtext').value);if(!bytes.length||bytes.length>192){$('feedback').textContent='Send accepts 1–192 bytes.';return;}command('send:'+Array.from(bytes,b=>b.toString(16).padStart(2,'0')).join(''));};
$('apply').onclick=()=>command(`settings:${$('preset').value},${$('baud').value}`);$('setinterface').onclick=()=>command('interface:'+$('interface').value);$('unpair').onclick=()=>command('unpair');connect();
</script></body></html>)BRIDGE";
}
